//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POLIFRONT_WEB_API.App_Code
{
    using System;
    using System.Collections.Generic;
    
    public partial class action_log
    {
        public int id_action_log { get; set; }
        public int id_utilisateurs { get; set; }
        public string nom_utils { get; set; }
        public string action { get; set; }
        public byte[] is_notif { get; set; }
        public System.DateTime date_enreg_act { get; set; }
    }
}
