//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POLIFRONT_WEB_API.App_Code
{
    using System;
    using System.Collections.Generic;
    
    public partial class grade
    {
        public int id { get; set; }
        public int niveau { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> date_insert { get; set; }
    }
}
