//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POLIFRONT_WEB_API.App_Code
{
    using Db_Core;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Data.SqlClient;

    public partial class traverse_frontiere
    {
        public int id_trav_front { get; set; }
        public int id_utilisateurs { get; set; }
        public string numero_interp { get; set; }
        public string numero_migrant { get; set; }
        public System.DateTime date_heure_tf { get; set; }
        public string departement_tf { get; set; }
        public string point_tf { get; set; }
        public string localite_tf { get; set; }
        public string provenance_tf { get; set; }
        public string destination_tf { get; set; }
        public string motif2deplac_tf { get; set; }
        public string poids_marchand { get; set; }
        public string valeur_monnaie_marcahnd { get; set; }
        public System.DateTime date_enreg_tf { get; set; }

        public traverse_frontiere(DataRow row)
        {
            parse(row);
        }

        private traverse_frontiere parse(DataRow row)
        {
            id_trav_front = int.Parse(row["id_trav_front"].ToString());
            id_utilisateurs = int.Parse(row["id_utilisateurs"].ToString());
            //...
            return this;
        }

        public static int addTraverseFrontiere(traverse_frontiere trav)
        {
            try
            {
                string sql = @"INSERT INTO dbo.traverse_frontiere
                                (id_utilisateurs
                                ,numero_interp
                                ,numero_migrant
                                ,date_heure_tf
                                ,departement_tf
                                ,point_tf
                                ,localite_tf
                                ,provenance_tf
                                ,destination_tf
                                ,motif2deplac_tf
                                ,poids_marchand
                                ,valeur_monnaie_marcahnd
                                ,date_enreg_tf)
                            VALUES
                                (?
                                ,?
                                ,?
                                ,?
                                ,?
                                ,?
                                ,?
                                ,?
                                ,?
                                ,?
                                ,?
                                ,?
                                ,GETDATE())";
                SqlStatement stmt = SqlStatement.FromString(sql, SqlConnString.POLIFRONT);
                stmt.SetParameters(
                    trav.id_utilisateurs,
                    trav.numero_interp,
                    trav.numero_migrant,
                    trav.date_heure_tf,
                    trav.departement_tf,
                    trav.point_tf,
                    trav.localite_tf,
                    trav.provenance_tf,
                    trav.destination_tf,
                    trav.motif2deplac_tf,
                    trav.poids_marchand,
                    trav.valeur_monnaie_marcahnd);
                return stmt.ExecuteNonQuery();
            }
            catch (Exception e)
            {
                Utils.ErrorLogging(System.Reflection.MethodBase.GetCurrentMethod().Name, e);
                return -1;
            }
        }
    }
}
