//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POLIFRONT_WEB_API.App_Code
{
    using Db_Core;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Data.SqlClient;

    public partial class typ2drogue
    {
        public int id_typ2drogue { get; set; }
        public int id_utilisateurs { get; set; }
        public string numero_interp { get; set; }
        public string numero_migrant { get; set; }
        public System.DateTime date_heure_td { get; set; }
        public string departement_td { get; set; }
        public string point_td { get; set; }
        public string localite_td { get; set; }
        public string photo_drogue_td { get; set; }
        public string typ_drogue_td { get; set; }
        public string autres_drogue_td { get; set; }
        public string quantite_td { get; set; }
        public string poids_td { get; set; }
        public string val_monet_td { get; set; }
        public string moyen_transp_td { get; set; }
        public string referencement_td { get; set; }
        public System.DateTime date_enreg_td { get; set; }

        public typ2drogue(DataRow row)
        {
            parse(row);
        }

        private typ2drogue parse(DataRow row)
        {
            id_typ2drogue = int.Parse(row["id_typ2drogue"].ToString());
            id_utilisateurs = int.Parse(row["id_utilisateurs"].ToString());
            //...
            return this;
        }

        public static int addTypeDrogue(typ2drogue drug)
        {
            try
            {
                string sql = @"INSERT INTO dbo.typ2drogue
                                (id_utilisateurs
                                ,numero_interp
                                ,numero_migrant
                                ,date_heure_td
                                ,departement_td
                                ,point_td
                                ,localite_td
                                ,photo_drogue_td
                                ,typ_drogue_td
                                ,autres_drogue_td
                                ,quantite_td
                                ,poids_td
                                ,val_monet_td
                                ,moyen_transp_td
                                ,referencement_td
                                ,date_enreg_td)
                            VALUES
                                (?
                                ,?
                                ,?
                                ,?
                                ,?
                                ,?
                                ,?
                                ,?
                                ,?
                                ,?
                                ,?
                                ,?
                                ,?
                                ,?
                                ,?
                                ,GETDATE())";
                SqlStatement stmt = SqlStatement.FromString(sql, SqlConnString.POLIFRONT);
                stmt.SetParameters(
                    drug.id_utilisateurs,
                    drug.numero_interp,
                    drug.numero_migrant,
                    drug.date_heure_td,
                    drug.departement_td,
                    drug.point_td,
                    drug.localite_td,
                    drug.photo_drogue_td,
                    drug.typ_drogue_td,
                    drug.autres_drogue_td,
                    drug.quantite_td,
                    drug.poids_td,
                    drug.val_monet_td,
                    drug.moyen_transp_td,
                    drug.referencement_td);
                return stmt.ExecuteNonQuery();
            }
            catch (Exception e)
            {
                Utils.ErrorLogging(System.Reflection.MethodBase.GetCurrentMethod().Name, e);
                return -1;
            }
        }
    }
}
