//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POLIFRONT_WEB_API.App_Code
{
    using Db_Core;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Data.SqlClient;

    public partial class victim_de_trait_sus
    {
        public int id_victim_de_trait_sus { get; set; }
        public int id_utilisateurs { get; set; }
        public string numero_interp { get; set; }
        public string numero_migrant { get; set; }
        public System.DateTime date_heure_vts { get; set; }
        public string departement_vts { get; set; }
        public string point_vts { get; set; }
        public string localite_vts { get; set; }
        public string provenance_vts { get; set; }
        public string finalidetedets_vts { get; set; }
        public System.DateTime dat2trait_vts { get; set; }
        public string relationavec_traf_vts { get; set; }
        public string referencement_vts { get; set; }
        public System.DateTime date_enreg_vts { get; set; }

        public victim_de_trait_sus(DataRow row)
        {
            parse(row);
        }

        private victim_de_trait_sus parse(DataRow row)
        {
            id_victim_de_trait_sus = int.Parse(row["id_victim_de_trait_sus"].ToString());
            id_utilisateurs = int.Parse(row["id_utilisateurs"].ToString());
            //...
            return this;
        }

        public static int addVictimeTraiteSuspectee(victim_de_trait_sus vic)
        {
            try
            {
                string sql = @"INSERT INTO dbo.victim_de_trait_sus
                                (id_utilisateurs
                                ,numero_interp
                                ,numero_migrant
                                ,date_heure_vts
                                ,departement_vts
                                ,point_vts
                                ,localite_vts
                                ,provenance_vts
                                ,finalidetedets_vts
                                ,dat2trait_vts
                                ,relationavec_traf_vts
                                ,referencement_vts
                                ,date_enreg_vts)
                            VALUES
                                (?
                                ,?
                                ,?
                                ,?
                                ,?
                                ,?
                                ,?
                                ,?
                                ,?
                                ,?
                                ,?
                                ,?
                                ,GETDATE())";
                SqlStatement stmt = SqlStatement.FromString(sql, SqlConnString.POLIFRONT);
                stmt.SetParameters(
                    vic.id_utilisateurs,
                    vic.numero_interp,
                    vic.numero_migrant,
                    vic.date_heure_vts,
                    vic.departement_vts,
                    vic.point_vts,
                    vic.localite_vts,
                    vic.provenance_vts,
                    vic.finalidetedets_vts,
                    vic.dat2trait_vts,
                    vic.relationavec_traf_vts,
                    vic.referencement_vts);
                return stmt.ExecuteNonQuery();
            }
            catch (Exception e)
            {
                Utils.ErrorLogging(System.Reflection.MethodBase.GetCurrentMethod().Name, e);
                return -1;
            }
        }
    }
}
